POST http://localhost:4001/patient/
Content-Type: application/json

{
        "firstname": "xz xz` ",
        "lastname": "zx` ",
        "email":"a@a.fr`",
        "password":"sac",
        "phone":"077777877"
}
#############################################################################################################################
POST http://localhost:4001/patient/auth
Content-Type: application/json

{
         "email":"toto@test.fr",
        "password":"1234"
}


#####
GET http://localhost:4001/patient/