POST http://localhost:3001/patient/
Content-Type: application/json

{
         "firstname": "",
         "lastname": "",
         "email":"",
        "password":"",
        "phone":""
}

#####
GET http://localhost:4001/patient/